"""Initial database schema

Revision ID: 19c8b62d5a1d
Revises: 
Create Date: 2026-02-12 12:17:52.901148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c8b62d5a1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('bots', sa.Column('hashed_api_key', sa.String(length=128), nullable=True))
    op.add_column('bots', sa.Column('balance', sa.Float(), nullable=False, server_default=sa.text('1000.0')))
    op.drop_column('bots', 'jwt_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('jwt_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('bots', 'balance')
    op.drop_column('bots', 'hashed_api_key')
    op.alter_column('audit_log', 'action',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
