"""bridge_social_and_financial_logic

Revision ID: fe662bbe0fb0
Revises: 19c8b62d5a1d
Create Date: 2026-02-12 16:00:57.969468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe662bbe0fb0'
down_revision: Union[str, Sequence[str], None] = '19c8b62d5a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_follows_followee_bot_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_bot_id'), table_name='follows')
    op.drop_constraint(op.f('uq_follow_pair'), 'follows', type_='unique')
    op.alter_column('hashtags', 'tag',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('hashtags', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ledger', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_ledger_bot_id'), table_name='ledger')
    op.create_unique_constraint(None, 'ledger', ['hash'])
    op.add_column('posts', sa.Column('prediction_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_posts_bot_id'), table_name='posts')
    op.create_foreign_key(None, 'posts', 'predictions', ['prediction_id'], ['id'])
    op.alter_column('predictions', 'claim_text',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_predictions_bot_id'), table_name='predictions')
    op.alter_column('resolutions', 'outcome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('resolutions', 'proof_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('resolutions_prediction_id_key'), 'resolutions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('resolutions_prediction_id_key'), 'resolutions', ['prediction_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('resolutions', 'proof_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('resolutions', 'outcome',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_predictions_bot_id'), 'predictions', ['bot_id'], unique=False)
    op.alter_column('predictions', 'claim_text',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=280),
               existing_nullable=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_index(op.f('ix_posts_bot_id'), 'posts', ['bot_id'], unique=False)
    op.drop_column('posts', 'prediction_id')
    op.drop_constraint(None, 'ledger', type_='unique')
    op.create_index(op.f('ix_ledger_bot_id'), 'ledger', ['bot_id'], unique=False)
    op.alter_column('ledger', 'transaction_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('hashtags', 'post_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hashtags', 'tag',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(op.f('uq_follow_pair'), 'follows', ['follower_bot_id', 'followee_bot_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_follows_follower_bot_id'), 'follows', ['follower_bot_id'], unique=False)
    op.create_index(op.f('ix_follows_followee_bot_id'), 'follows', ['followee_bot_id'], unique=False)
    op.alter_column('audit_log', 'metadata_json',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
